filepath='D:\project\biyesheji\Code\data\MERRA_2\AOD\';
year=2014;
filename=strcat('MerAOD',num2str(year),'.mat');
file_full_name = fullfile(filepath,filename);
MerAODdata=load(file_full_name);
t = MerAODdata.MerAOD.time;
time = datetime(t,'ConvertFrom','datenum');
% 提取四种气溶胶类型
Biyesheji.y2014 = struct(...
'MERRA_TOTEXTTAU',[MerAODdata.MerAOD.TOTEXTTAU],...
'MERRA_BCEXTTAU',[MerAODdata.MerAOD.BCEXTTAU],...
'MERRA_DUEXTTAU',[MerAODdata.MerAOD.DUEXTTAU],...
'MERRA_OCEXTTAU',[MerAODdata.MerAOD.OCEXTTAU],...
'MERRA_SUEXTTAU',[MerAODdata.MerAOD.SUEXTTAU],...
'time',[time]);
clear MerAODdata
beep
year=2015;
filename=strcat('MerAOD',num2str(year),'.mat');
file_full_name = fullfile(filepath,filename);
MerAODdata=load(file_full_name);
t = MerAODdata.MerAOD.time;
time = datetime(t,'ConvertFrom','datenum');
% 提取四种气溶胶类型
Biyesheji.y2015 = struct(...
'MERRA_TOTEXTTAU',[MerAODdata.MerAOD.TOTEXTTAU],...
'MERRA_BCEXTTAU',[MerAODdata.MerAOD.BCEXTTAU],...
'MERRA_DUEXTTAU',[MerAODdata.MerAOD.DUEXTTAU],...
'MERRA_OCEXTTAU',[MerAODdata.MerAOD.OCEXTTAU],...
'MERRA_SUEXTTAU',[MerAODdata.MerAOD.SUEXTTAU],...
'time',[time]);
clear MerAODdata
beep
year=2016;
filename=strcat('MerAOD',num2str(year),'.mat');
file_full_name = fullfile(filepath,filename);
MerAODdata=load(file_full_name);
t = MerAODdata.MerAOD.time;
time = datetime(t,'ConvertFrom','datenum');
% 提取四种气溶胶类型
Biyesheji.y2016 = struct(...
'MERRA_TOTEXTTAU',[MerAODdata.MerAOD.TOTEXTTAU],...
'MERRA_BCEXTTAU',[MerAODdata.MerAOD.BCEXTTAU],...
'MERRA_DUEXTTAU',[MerAODdata.MerAOD.DUEXTTAU],...
'MERRA_OCEXTTAU',[MerAODdata.MerAOD.OCEXTTAU],...
'MERRA_SUEXTTAU',[MerAODdata.MerAOD.SUEXTTAU],...
'time',[time]);
clear MerAODdata
beep
year=2017;
filename=strcat('MerAOD',num2str(year),'.mat');
file_full_name = fullfile(filepath,filename);
MerAODdata=load(file_full_name);
t = MerAODdata.MerAOD.time;
time = datetime(t,'ConvertFrom','datenum');
% 提取四种气溶胶类型
Biyesheji.y2017 = struct(...
'MERRA_TOTEXTTAU',[MerAODdata.MerAOD.TOTEXTTAU],...
'MERRA_BCEXTTAU',[MerAODdata.MerAOD.BCEXTTAU],...
'MERRA_DUEXTTAU',[MerAODdata.MerAOD.DUEXTTAU],...
'MERRA_OCEXTTAU',[MerAODdata.MerAOD.OCEXTTAU],...
'MERRA_SUEXTTAU',[MerAODdata.MerAOD.SUEXTTAU],...
'time',[time]);
clear MerAODdata
beep
year=2018;
filename=strcat('MerAOD',num2str(year),'.mat');
file_full_name = fullfile(filepath,filename);
MerAODdata=load(file_full_name);
t = MerAODdata.MerAOD.time;
time = datetime(t,'ConvertFrom','datenum');
% 提取四种气溶胶类型
Biyesheji.y2018 = struct(...
'MERRA_TOTEXTTAU',[MerAODdata.MerAOD.TOTEXTTAU],...
'MERRA_BCEXTTAU',[MerAODdata.MerAOD.BCEXTTAU],...
'MERRA_DUEXTTAU',[MerAODdata.MerAOD.DUEXTTAU],...
'MERRA_OCEXTTAU',[MerAODdata.MerAOD.OCEXTTAU],...
'MERRA_SUEXTTAU',[MerAODdata.MerAOD.SUEXTTAU],...
'time',[time]);
clear MerAODdata
beep
% load('bs.mat')
% tf = isbetween(A,tlower,tupper)
% [c,r,f]=size(Biyesheji.y2017.MERRA_TOTEXTTAU);
% A = zeros(c,r);
% piexl=0;
% for i =1:c
%     for j = 1:r
%         for l = 1:f
%         piexl = piexl + Biyesheji.y2017.MERRA_TOTEXTTAU(i,j,f);
%         A(i,j)=piexl;
%         end
%     end
% end
% subplot(121);imshow(A);
% subplot(122);imshow(AA);
% AA=Biyesheji.y2017.MERRA_TOTEXTTAU(:,:,1);
% mean2(A)